### PR TITLE
SAND-mask: An Enhanced Gradient Masking Strategy for the Discovery of Invariances in Domain Generalization

### PR DESCRIPTION
**Pull request by shahtalebi**
Our proposed "SAND-mask" technique offers the SOTA results on ColoredMNIST with a 6% improvement in the Oracle setting plus competitive results over other datasets. 
The paper can be found [here](https://arxiv.org/abs/2106.02266).

### CODE REVIEW

**Comment by lopezpaz** [comment]
Could you edit this PR as to modify only `algorithms.py` and `hparams_registry.py`? You can also modify `README.md` but only to add one line listing your algorithm (currently your edits to `README.md` look like those you would like for your repository).

**Comment by lopezpaz** [comment]
Please remove `.idea` folder.

**Comment by shahtalebi** [comment]
Thank you, Mr. Lopezpaz, for your help and guidance. I update the repo and the pull request accordingly. Please let me know if any other change is required. Thank you so much.

**Comment by lopezpaz** [comment]
Thank you for your contribution!

**Pull request merged**
