### PR TITLE
Adding ADRMX

### PR DESCRIPTION
**Pull request by berkerdemirel**
In this PR we are adding the implementation of ADRMX: Additive Disentanglement of Domain Features with Remix Loss from https://arxiv.org/abs/2308.06624. 

Tested with the following command:

```
python -m domainbed.scripts.train --data_dir=<data_path> --algorithm ADRMX --dataset PACS
```

### CODE REVIEW

**Comment by piotr-teterwak** [comment]
Hi @berkerdemirel , could you run the unit tests, which are launched as described at the bottom of the README.md?

Apologies for the extended delay.

**Comment by berkerdemirel** [comment]
Hello, no worries! I ran the unit tests, and corrected one size mismatch.

**Comment by berkerdemirel** [comment]
Here is the screenshot of running [unit tests.](https://drive.google.com/file/d/1AdAumZOgCvMQXX-RJjRpo25l82_jAuqW/view?usp=sharing) I similarly encountered dependency conflicts while testing Fishr with the package backpack-for-pytorch. I can confirm that requirements.txt file provided by @nktoan solves the package conflicts.

Best regards,

**Comment by piotr-teterwak** [comment]
Thanks! There are also the tests depending on a data directory, run like this:

`DATA_DIR=/my/datasets/path python -m unittest discover`. Could you run this too?

**Comment by piotr-teterwak** [comment]
Also, could you add to the README.md? Thanks!

**Comment by berkerdemirel** [comment]
Oh sorry I thought dataset tests are not for the method additions. Here is the [screenshot](https://drive.google.com/file/d/196zBVYHsaWqoTmQds_Vy4KMFUubIy6cc/view?usp=sharing).

I added the method to README.md too. Thanks!

**Comment by piotr-teterwak** [comment]
Looks good! Thanks for your contribution!

**Pull request merged**
