### PR TITLE
add method: Uniform Risk Minimization (URM)

### PR DESCRIPTION
**Pull request by kiranchari**
I am first author of "Uniformly Distributed Feature Representations for Fair and Robust Learning" (TMLR 2024) paper. Link: https://openreview.net/forum?id=PgLbS5yp8n

In this pull request I am adding code for the proposed Uniform Risk Minimization (URM) method for domain generalization. The key idea is to encourage the distribution of feature representations learned by the encoder/featurizer to be uniformly distributed. The paper provides theoretical and empirical support for the proposed method for domain generalization and also robustness to sub-population shifts.

Changes include:

-  added `URM` class in `algorithms.py`
- added hyper-parameters in `hparams_registry.py`
- added method and link to paper in README.md
- modified `networks.py` and `lib/wide_resnet.py` to add an activation function to the output of the featurizer/encoder networks (before the linear classifier). This does not affect other algorithms in DomainBed as the default activation is nn.Identity(): https://github.com/kiranchari/DomainBed/blob/2b47e0ce5f6ad6560c93ba4a40c3aa617ca78053/domainbed/lib/wide_resnet.py#L87

Thank you.

### CODE REVIEW

**Comment by piotr-teterwak** [comment]
Hi! Thank you for the contribution. I will take a look early next week.

**Comment by piotr-teterwak** [comment]
Hi @kiranchari  , could you run the unit tests, which are launched as described at the bottom of the README.md?

**Comment by kiranchari** [comment]
Hi @piotr-teterwak, I ran the tests and they appear to pass (see attached screenshot). Thanks
unittest

**Comment by kiranchari** [comment]
Hi @piotr-teterwak, I tried running the tests with DATA_DIR set (`/home/user/project/datasets`)
 and with all the datasets downloaded in that directory, but I am getting some runtime errors that are not related to my method. Please see attached error log here: [unittest_error_log.txt](https://github.com/user-attachments/files/18139149/unittest_error_log.txt)

1. There is an error in loading the FMOW dataset: `ValueError: time data "2011-02-07T02:48:56.643Z" doesn't match format "%Y-%m-%dT%H:%M:%S%z", at position 92`. I have the dataset in `/home/user/project/datasets/fmow_v1.1`
2. There is an error loading Spawrious dataset as the code is looking for the images in the root of the DATA_DIR ( `/home/user/project/datasets`) rather than inside `/home/user/project/datasets/spawrious224`

**Comment by kiranchari** [comment]
@piotr-teterwak Please let me know any tips to prevent these errors, thanks!

**Comment by piotr-teterwak** [comment]
Hi @kiranchari can you try version , pandas==1.5.3, for the datetime error? 

For the spawrious error, I will file an issue. Also, can you add a point of contact (ie email) in the README for this particular algorithm?

Otherwise, looks good to me.

**Comment by kiranchari** [comment]
Thanks @piotr-teterwak. Installing pandas==1.5.3 seems to have fixed the datetime issue: 
[unittest_v2.txt](https://github.com/user-attachments/files/18264909/unittest_v2.txt)

I have updated the README with a point of contact (email). 

Thanks!

**Comment by piotr-teterwak** [comment]
LGTM

**Pull request merged**
